shape: sequence_diagram
Alice -> Lido: ETH
Lido -> ethereum network: ETH
Lido -> Alice: stETH
ethereum network -> Alice: earns staking rewards

Bob -> Aave : DAI
Charles -> Aave: DAI
Aave -> Charls: USDC
Aave -> Bob: interest
Charls -> Aave: interest
